### PyTorch Packages

- torch : The top-level PyTorch package and tensor library  
- torch.nn : A subpackage that contains modules and extensible classes for building neural networks  
- torch.autograd : A subpackage that support all the differentiable Tensor operations in PyTorch  
- torch.nn.functional : A functional interface that contains typical operations used for building neural networks like loss functions, activation functions, and convolution operations   
- torch.optim : A subpackage that contains standard optimization operations like SGC and Adam  
- torch.utils : A subpackage that contains utility classes like data sets and data loaders that make data preprocessing easier  
- torchvision : A package that provides access to popular datasets, model architechtures, and image transformation for computer vision  


### torch
top-level method
    - torch.tensor : create tensor with existing data
    - torch.eye: create diagonal matrix / tensor
    - torch.zeros : create tensor filled with zeros
    - torch.ones : create tensor filled with ones
    - torch.from_numpy : create tensor from array
    - torch.randn : creat random tensor

In [8]:
import torch

In [21]:
torch.tensor([1,2,3], requires_grad=False, dtype = torch.float32)

tensor([1., 2., 3.])

In [17]:
import numpy as np
# torch.tensor uses np.array as an input
t = torch.tensor(np.array([[1,2,3],[4,5,6]]))
t

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [20]:
torch.eye(3, dtype=torch.double)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

In [22]:
torch.zeros(3)

tensor([0., 0., 0.])

In [27]:
torch.ones(3)

tensor([1., 1., 1.])

In [38]:
a = np.arange(6)
t = torch.from_numpy(a)
print(t)

tensor([0, 1, 2, 3, 4, 5], dtype=torch.int32)


In [43]:
torch.randn((3,3))

tensor([[-1.8366,  0.6943, -0.0380],
        [ 0.6823,  0.5980,  0.8796],
        [-0.6557,  0.2945,  1.6147]])

torch.tensor's method/argument
    - dtype
    - device
    - requires_grad
    - size()
    - shape
    - ndim

In [26]:
print(t.dtype)

torch.float32


In [28]:
print(t.device)

cpu


In [29]:
print(t.requires_grad)

False


In [30]:
t.size()

torch.Size([3])

In [31]:
t.shape

torch.Size([3])

In [32]:
t.ndim

1

### Indexing : like numpy

In [34]:
# indexing like numpy array
t = torch.zeros((3,3))
t[:,:]

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### torch.nn : basic building block for graphs

(https://pytorch.org/docs/stable/nn.html)

 - Containers
     - nn.Module : Base class for all neural network modules
     - nn.Sequential : A sequential container
 - Convolution Layers
     - nn.Conv1d
     - nn.Conv2d
     - nn.Conv3d
 - Pooling layers
     - nn.MaxPool1d
     - nn.MaxPool2d
     - nn.MaxPool3d
 - Non-linear activations
     - nn.ReLU
     - nn.Tanh
     - nn.Softmax
 - Normalization Layers
     - nn.BatchNorm1d
     - nn.BatchNorm2d
 - Recurrent Layers
     - nn.RNN
     - nn.LSTM
     - nn.GRU
 - Linear Layers
     - nn.Linear
 - Dropout Layers
     - nn.Dropout
 - Sparse Layers
     - nn.Embedding
 - Distance Functions
     - nn.CosineSimilarity
 - Loss Functions
     - nn.L1Loss
     - nn.MSELoss
     
 - nn.Linear
 - nn.Parameter
 - nn.Module.
     - nn.Module.parameters()
    

### torch.autograd : Automatic Differntiation package

(https://pytorch.org/docs/stable/autograd.html)

In [39]:
import torch
from torch import autograd

x1 = torch.tensor(4,requires_grad= True, dtype = torch.float32)
x2 = torch.tensor(2,requires_grad= True, dtype = torch.float32)
x3 = torch.tensor(7,requires_grad= True, dtype = torch.float32)
x4 = torch.tensor(1,requires_grad= True, dtype = torch.float32)

In [40]:
h1 = 2 * x1 * x2
h2 = 3 * x3 * x4
f = 5 * (h1 + h2)
h1, h2, f

(tensor(16., grad_fn=<MulBackward0>),
 tensor(21., grad_fn=<MulBackward0>),
 tensor(185., grad_fn=<MulBackward0>))

In [41]:
df_dx = autograd.grad(outputs =f, inputs = [x1,x2,x3,x4])
df_dx

(tensor(20.), tensor(40.), tensor(15.), tensor(105.))

### torch.optim : a pakage implementing various optimization algorithms

[example1]   
from torch import optim  
opt = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)  
opt = optim.Adam([var1, var2], lr=0.0001)  

opt.step()  
opt.zero_grad()

### torch.utils
    - torch.utils.data.DataLoader : responsible for managing batches, gives us each minibath automatically
    

[example1]

 - Train/Test/Validation dataset  
 
from torch.utils.data import DataLoader

train_ds = TensorDataset(x_train, y_train)  
train_dl = DataLoader(train_ds, batch_size=bs,shuffle=True)  

for xb,yb in train_dl:  
    pred = model(xb)  